"""``render_report_markdown``: the results.md artifact renderer (a pure formatter)."""

from __future__ import annotations

import re

from arc_lab.program_search.ladders.report import (
    _estimate_raw_cost,
    _fit_b_eff,
    render_report_markdown,
)


def _compact(text: str) -> str:
    """Collapse table-cell padding so assertions are layout-independent."""
    return re.sub(r" +", " ", text)


_COST: dict[str, object] = {
    "jump_costs": {"rot180": 13486, "mirror_recolor": 13824},
    "jump_costs_to_first": {"rot180": 228, "mirror_recolor": 938},
    "top_jump_cost": 26401,
    "top_jump_cost_to_first": 7206,
    "laddered_marginal_considered": 53711,
    "laddered_marginal_to_first": 8372,
    "laddered_end_to_end_considered": 200280,
    "raw_considered": 6743,
    "raw_solved": False,
    "raw_censored": True,
    "off_chain_top_solved": True,
    "amortization_ratio_considered": None,
    "budget_compression_depth": {"raw_depth": 4, "max_jump_depth": 2},
}

_REPORT: dict[str, object] = {
    "ladder": {"train_corpus": {"name": "al1-mirror:train"}},
    "shape": {
        "height": 3,
        "raw_depth_profile": [4],
        "max_jump_depth": 2,
        "validity_window": [2, 2],
        "lint_ok": True,
    },
    "certificate": {
        "admitted": True,
        "tractable_jumps": {1: True, 2: True},
        "no_skip_paths": {1: True, 2: False},
        "demonstration_health": {1: 1.0, 2: 0.5},
    },
    "climb_trace": [
        {
            "iteration": 0,
            "wake_solved": ["rot180-00"],
            "wake_considered": 33715,
            "minted": ["abs0"],
            "converged": False,
        },
        {
            "iteration": 1,
            "wake_solved": [],
            "wake_considered": 34560,
            "minted": [],
            "converged": True,
        },
    ],
    "rung_recovery": [
        {"rung": "rot180", "level": 1, "recovered": True, "matched_by": ["abs0"]},
        {"rung": "mirror_recolor", "level": 2, "recovered": False, "matched_by": []},
    ],
    "cost_matrix": [
        {
            "task_id": "rot180-00",
            "rung": "rot180",
            "columns": {
                "0": {
                    "considered": 6743,
                    "solved": True,
                    "solve_generation": 2,
                    "first_solution_index": 114,
                    "cheapest_solution_index": 114,
                    "b_eff": 24.55,
                },
                "1": {
                    "considered": 6912,
                    "solved": False,
                    "solve_generation": None,
                    "first_solution_index": None,
                    "cheapest_solution_index": None,
                    "b_eff": None,
                },
            },
        }
    ],
    "comparisons": {
        "loop_overhead_factor": 200280 / 53711,
        "marginal_rung_value": [
            {
                "rung": "rot180",
                "layer_above": "mirror_recolor",
                "cost_without_rung": 13486,
                "cost_with_rung": 13824,
                "ratio": 13486 / 13824,
                "censored": True,
                "own_tasks_to_first_without": 228,
                "own_tasks_to_first_with": 226,
                "own_tasks_speedup": 228 / 226,
            }
        ],
        "vocabulary_tax": [
            {
                "rung": "rot180",
                "at_own_level": 13486,
                "at_full_library": 52802,
                "factor": 52802 / 13486,
            }
        ],
        "enablement": {"1": ["mirror-recolor-1-2"], "2": []},
    },
    "cost": _COST,
}


def test_renders_every_section_from_the_report_dict() -> None:
    text = _compact(render_report_markdown(_REPORT))
    assert "# Ladder results: al1-mirror" in text  # the :train suffix is stripped
    assert "**ADMITTED**" in text
    assert "| 1 | yes | yes | 1.0 |" in text and "| 2 | yes | no | 0.5 |" in text
    assert "| 0 | 1: `rot180-00` | 33,715 | `abs0` | no |" in text
    assert "| 1 | 0 | 34,560 | - | yes |" in text
    assert "| `mirror_recolor` | 2 | no | - |" in text
    assert "Laddered marginal: 53,711" in text and "- top jump: 26,401" in text
    assert "a full-budget FAILURE, not a raw cost" in text  # never presented as the raw cost
    assert "d_raw 4 -> max jump depth 2" in text
    assert text.startswith("<!-- Generated by render_report_markdown")


def test_renders_cost_matrix_and_per_task_solution_detail() -> None:
    text = _compact(render_report_markdown(_REPORT))
    # Cost matrix: solved cells marked, unsolved bare (a censored lower bound).
    assert "| `rot180-00` | rot180 | 6,743 * | 6,912 |" in text
    # Per-task detail lists only solved cells, with generation + first/cheapest index + b_eff.
    assert "| `rot180-00` | L_0 | 2 | 114 | 114 | 6,743 | 24.55 |" in text
    assert "| `rot180-00` | L_1 |" not in text  # unsolved cell omitted from the detail table


def test_renders_comparisons_with_both_currencies() -> None:
    text = _compact(render_report_markdown(_REPORT))
    assert "### Two currencies -- read this first" in text
    assert "cost-paid-full: 53,711 vs cost-to-first: 8,372" in text
    assert "- jump `rot180`: 228" in text
    assert "**Loop-overhead factor**: 3.73x" in text
    # The speedup (cost-to-first on the rung's own tasks) is the honest measure and leads; the
    # censored paid-full layer-above ratio is retained but demoted.
    assert "| `rot180` | 228 | 226 | **1.01x** | 0.98x vs `mirror_recolor` | yes |" in text
    assert "| `rot180` | 13,486 | 52,802 | 3.92x |" in text  # vocabulary tax
    assert "`L_1` (vs `L_0`): `mirror-recolor-1-2`" in text
    assert "`L_2` (vs `L_1`): nothing new" in text
    # The censoring caveat must be present so a sub-1.0x ratio is not read as a slowdown.
    assert "reachability" in text


def test_b_eff_fits_growth_only_over_pre_saturation_rounds() -> None:
    # Un-truncated rounds: composed 10 -> 40 -> 160 is a clean 4x per round.
    clean = [
        {"composed": 10, "pool_size_before_truncation": 10, "pool_size_end": 10},
        {"composed": 40, "pool_size_before_truncation": 40, "pool_size_end": 40},
        {"composed": 160, "pool_size_before_truncation": 160, "pool_size_end": 160},
    ]
    assert _fit_b_eff(clean) == 4.0
    # A round's composed count is a function of its INPUT pool, so the round that truncates its
    # own output is still a genuine measurement; only the round AFTER it composes from a capped
    # pool and would understate growth. Here 10 -> 40 -> 160 all count (4.0); the capped 200 does
    # not (including it would drag the fit to ~2.7).
    saturated = [
        *clean[:2],
        {"composed": 160, "pool_size_before_truncation": 900, "pool_size_end": 300},
        {"composed": 200, "pool_size_before_truncation": 900, "pool_size_end": 300},
    ]
    assert _fit_b_eff(saturated) == 4.0
    assert _fit_b_eff(clean[:1]) is None  # a single round yields no ratio


def test_raw_cost_is_extrapolated_not_measured() -> None:
    # Raw is never run for a real ladder (intractable by construction) -- it is projected from the
    # rounds the Floor search DID complete. Clean 10x growth through depth 2, projected to d_raw=4.
    generations = [
        {"composed": 10},
        {"composed": 100},
        {"composed": 1000},
    ]
    estimate = _estimate_raw_cost(generations, d_raw=4, depth_limit=2)
    assert estimate["available"] is True
    assert estimate["rounds_extrapolated"] == 2
    assert estimate["growth_ratio_geometric"] == 10.0
    assert estimate["growth_ratio_last"] == 10.0
    # observed 1,110 + 10,000 + 100,000; both fits agree when growth is constant.
    assert estimate["estimate_low"] == estimate["estimate_high"] == 111_110


def test_raw_estimate_brackets_when_growth_accelerates() -> None:
    # AL1's real shape: growth accelerates (9.3x then 65x), so the geometric-mean fit and the
    # last-ratio fit disagree -- the bracket must span them rather than pick one.
    estimate = _estimate_raw_cost(
        [{"composed": 11}, {"composed": 102}, {"composed": 6630}], d_raw=4, depth_limit=2
    )
    assert estimate["growth_ratio_geometric"] == 24.55
    assert estimate["growth_ratio_last"] == 65.0
    low, high = estimate["estimate_low"], estimate["estimate_high"]
    assert isinstance(low, int) and isinstance(high, int)
    assert low < high  # the fits bracket rather than agree
    assert 4_000_000 < low < 4_300_000  # ~4.2M
    assert 28_000_000 < high < 29_000_000  # ~28.4M


def test_b_eff_ignores_a_round_a_stop_limit_cut_short() -> None:
    """The saturation guard cannot catch this one: an aborted round records
    ``pool_size_end == pool_size_before_truncation`` (it never reached its truncation), so it looks
    unsaturated. Unfiltered, its partial ``composed`` becomes the fit's endpoint and understates
    growth -- here 10x would read as 1.4x."""
    complete = [
        {"composed": 10, "pool_size_before_truncation": 10, "pool_size_end": 10},
        {"composed": 100, "pool_size_before_truncation": 100, "pool_size_end": 100},
    ]
    aborted = {
        "composed": 20,
        "pool_size_before_truncation": 120,
        "pool_size_end": 120,
        "incomplete": True,
    }
    assert _fit_b_eff(complete) == 10.0
    assert _fit_b_eff([*complete, aborted]) == 10.0


def test_raw_estimate_drops_a_round_a_stop_limit_cut_short() -> None:
    """A censored run is exactly the input this estimator exists to consume, so the ``incomplete``
    filter is load-bearing, not hygiene.

    The truncated round is an arbitrary fraction of its real size and always last, so both fitted
    ratios read it as collapse rather than growth. The estimate does not fail loudly -- ``min``/
    ``max`` keep the bracket ordered and it still looks well-formed. It is simply WRONG by two
    orders of magnitude, which is the more dangerous failure: 1.1e3 where the truth is 1.1e5.
    """
    complete = [{"composed": 10}, {"composed": 100}, {"composed": 1000}]
    censored = [*complete, {"composed": 3, "incomplete": True}]

    filtered = _estimate_raw_cost(censored, d_raw=4, depth_limit=2)
    assert filtered == _estimate_raw_cost(complete, d_raw=4, depth_limit=2)
    assert filtered["estimate_low"] == filtered["estimate_high"] == 111_110

    # The number the filter prevents: a plausible-looking estimate ~100x too small, because the
    # partial round (3 composed, against the previous round's 1000) reads as decay.
    unfiltered = _estimate_raw_cost([*complete, {"composed": 3}], d_raw=5, depth_limit=3)
    high = unfiltered["estimate_high"]
    assert isinstance(high, int)
    assert high < 2_000  # vs the correct 111_110 -- silently, with no error raised


def test_raw_estimate_unavailable_without_enough_signal() -> None:
    # Fewer than two rounds gives no ratio; d_raw within the budget means nothing to project.
    assert _estimate_raw_cost([{"composed": 10}], d_raw=4, depth_limit=2)["available"] is False
    assert (
        _estimate_raw_cost([{"composed": 10}, {"composed": 100}], d_raw=2, depth_limit=2)[
            "available"
        ]
        is False
    )


def test_renders_the_raw_estimate_and_its_caveats() -> None:
    report = {
        **_REPORT,
        "cost": {
            **_COST,
            "raw_estimate": {
                "available": True,
                "d_raw": 4,
                "observed_through_depth": 2,
                "rounds_extrapolated": 2,
                "observed_composed": [11, 102, 6630],
                "growth_ratio_geometric": 24.55,
                "growth_ratio_last": 65.0,
                "estimate_low": 4_165_594,
                "estimate_high": 28_449_443,
                "caveats": ["assumes a pool large enough not to bind"],
            },
            "amortization_ratio_estimated": {
                "low": 4_165_594 / 53711,
                "high": 28_449_443 / 53711,
            },
        },
    }
    text = _compact(render_report_markdown(report))
    assert "**Raw cost (estimated): 4,165,594 - 28,449,443 considered.**" in text
    assert "Raw is never measured" in text
    assert "**Amortization ratio (estimated): 78x - 530x**" in text
    assert "caveat: assumes a pool large enough not to bind" in text


def test_ratio_renders_when_raw_is_uncensored() -> None:
    cost: dict[str, object] = {
        **_COST,
        "raw_considered": 500000,
        "raw_solved": True,
        "raw_censored": False,
        "amortization_ratio_considered": 500000 / 53711,
    }
    text = render_report_markdown({**_REPORT, "cost": cost})
    assert "Amortization considered-ratio (measured): 9.31" in text
    assert "a full-budget FAILURE" not in text  # raw actually solved, so no failure caveat


def test_the_raw_estimate_carries_its_measured_unreliability() -> None:
    """The bracket is NOT a containment claim, and the report has to say so.

    Validated 2026-07-23 against measured raw cost (experiments/2026-07-23-estimator-validation/):
    it held in 2 of 10 cells. On accelerating-growth floors both fits under-project by up to 269x;
    on finite-space floors both over-project. A consumer reading `estimate_low`/`estimate_high` as
    "the answer is in here" is reading it wrong, so the returned caveats carry the measurement.
    """
    estimate = _estimate_raw_cost(
        [{"composed": 11}, {"composed": 102}, {"composed": 6630}], d_raw=4, depth_limit=2
    )
    caveats = estimate["caveats"]
    assert isinstance(caveats, list)
    assert any("2/10" in str(c) for c in caveats)
    assert any("under-project" in str(c) for c in caveats)
    assert any("over-project" in str(c) for c in caveats)
    assert "2026-07-23" in str(estimate["validated"])
