"""``LadderSpec`` + ``lint()`` on ladder #1 (``al1-mirror``): the verified tractability sandwich."""

from __future__ import annotations

import dataclasses

from arc_lab.program_search.execution.model.study_spec import TargetAbstraction
from arc_lab.program_search.ladders.registry import make_ladder
from arc_lab.program_search.ladders.shape import LadderShape
from arc_lab.program_search.ladders.spec import (
    Demonstration,
    DemonstrationKind,
    _rung_argument_columns,
)
from arc_lab.program_search.search.search_engine import BottomUpSearchEngine
from arc_lab.program_search.substrate.primitives.control import IF
from arc_lab.program_search.substrate.program import Apply, Const, If, Input, Param
from arc_lab.program_search.substrate.types import BOOL, COLOR, GRID


def _failed(shape: LadderShape, check: str) -> bool:
    return any(finding.check == check and not finding.ok for finding in shape.findings)


def test_ladder1_lints_ok_with_the_verified_sandwich() -> None:
    shape = make_ladder("al1-mirror").lint()
    assert shape.ok
    assert shape.height == 3
    assert shape.validity_window == (2, 2)
    assert shape.raw_depth_profile == (4,)
    by_name = {rung.name: rung for rung in shape.rungs}
    assert by_name["rot180"].jump_depth == 2
    assert by_name["rot180"].double_jump_depth == 3  # mirror_recolor inlined over L0 (skip rot180)
    assert by_name["rot180"].fan_in == 0  # rot180 uses only floor primitives
    assert by_name["mirror_recolor"].jump_depth == 2
    # The last bridging rung's double jump comes from the layer above it -- the Top: the top
    # solution inlined over L_1 (skip mirror_recolor) has depth 3.
    assert by_name["mirror_recolor"].double_jump_depth == 3
    assert by_name["mirror_recolor"].fan_in == 1  # references rot180 once


def test_oracle_chain_grows_by_one_rung_per_level() -> None:
    spec = make_ladder("al1-mirror")
    assert "rot180" not in spec.floor()
    assert "rot180" in spec.oracle_library(1)
    assert "mirror_recolor" not in spec.oracle_library(1)
    assert "mirror_recolor" in spec.oracle_library(2)


def test_rung_tasks_resolve_from_demonstration_ids() -> None:
    spec = make_ladder("al1-mirror")
    rot180_ids = {t.task.task_id for t in spec.rung_tasks(1)}
    assert rot180_ids == {"rot180-00", "rot180-01"}


def test_render_marks_ok_and_lists_the_rungs() -> None:
    text = make_ladder("al1-mirror").render()
    assert "al1-mirror" in text and "OK" in text and "rot180" in text and "mirror_recolor" in text


def test_render_carries_derived_facts_only() -> None:
    # spec.md holds what FOLLOWS from the ladder's source, never a restatement of it: the
    # `.ladder` file owns templates, tasks and the config block (LADDER-FORMAT.md).
    text = make_ladder("al1-mirror").render()
    assert "al1-mirror.ladder" in text  # the pointer to the source of truth
    assert "`flip_h(flip_v(#0))`" not in text  # r_1's template belongs to the file
    assert "map_color(mirror_recolor(input, 1, 2), 3, 4)" not in text  # ditto the top solution
    assert "`rot180-00`" not in text  # ditto the corpus map
    # The RESOLVED config is genuinely derived (frozen default + the file's overrides), as is the
    # demonstration kind (from each solution's shape) and every depth.
    assert "## Reference config (resolved)" in text
    assert "depth_limit: `2`" in text and "AntiunifyPairs" in text
    assert "considered_limit: `50000`" in text
    assert "full_solution" in text
    assert "d=2, needs depth_limit 2, over `L_2`" in text


def test_render_separates_verification_and_shows_shape() -> None:
    # Verification: the static lint's verdict is labeled as such, and the empirical certificate
    # is explicitly delegated to results.md. Shape: dependency edges with multiplicity.
    text = make_ladder("al1-mirror").render()
    assert "## Verification" in text
    assert "Static lint" in text and "**OK**" in text
    assert "Empirical certificate" in text and "results.md" in text
    assert "## Shape" in text and "pure telescope" in text
    assert "r_1 `rot180`: floor primitives only" in text
    assert "r_2 `mirror_recolor`: `rot180` x1" in text
    assert "top `top-00`: `mirror_recolor` x1" in text
    assert text.startswith("<!-- Generated by LadderSpec.render()")


def test_lint_catches_a_bare_primitive_rung() -> None:
    # A depth-1 rung restates a primitive already in L_{i-1}: it belongs to a lower rung and
    # buys no depth (demonstration relationship (1) -- a rung is a PROPER composition).
    spec = make_ladder("al1-mirror")
    bare = dataclasses.replace(
        spec.rungs[0],
        target_abstraction=TargetAbstraction(
            name="rot180", template=Apply("flip_h", (Param(0, GRID),))
        ),
    )
    shape = dataclasses.replace(spec, rungs=(bare, spec.rungs[1])).lint()
    assert not shape.ok
    assert _failed(shape, "proper-composition[rot180]")


def test_lint_catches_a_rung_the_one_above_never_calls() -> None:
    # Structural degeneracy: rung 2 is a fine depth-2 composition but never calls rot180, so the
    # rung below is unused and the ladder telescopes vacuously at that link.
    spec = make_ladder("al1-mirror")
    unused_below = dataclasses.replace(
        spec.rungs[1],
        target_abstraction=TargetAbstraction(
            name="mirror_recolor",
            template=Apply(
                "flip_h",
                (Apply("map_color", (Param(0, GRID), Param(1, COLOR), Param(2, COLOR))),),
            ),
        ),
    )
    shape = dataclasses.replace(spec, rungs=(spec.rungs[0], unused_below)).lint()
    assert not shape.ok
    assert _failed(shape, "rung-referenced[rot180]")


def test_lint_catches_a_top_that_never_uses_the_top_rung() -> None:
    # A top that never calls r_k isn't standing on the ladder at all.
    spec = make_ladder("al1-mirror")
    detached_top = dataclasses.replace(spec.top, reference_solutions=(Apply("flip_h", (Input(),)),))
    shape = dataclasses.replace(spec, top=detached_top).lint()
    assert not shape.ok
    assert _failed(shape, "top-uses-top-rung")


def test_lint_catches_a_budget_that_makes_the_raw_top_reachable() -> None:
    # A budget deep enough to reach the raw top (d_raw=4) breaks the raw-intractable claim.
    spec = make_ladder("al1-mirror")
    deep = dataclasses.replace(spec.reference_config.budget, depth_limit=5)
    bad = dataclasses.replace(spec, reference_config=spec.reference_config.with_(budget=deep))
    shape = bad.lint()
    assert not shape.ok
    assert any(finding.check == "raw-intractable" and not finding.ok for finding in shape.findings)


def test_lint_catches_the_al14_literal_collapse_statically() -> None:
    # al14's stated solutions compute train-constant indices from enumerable INT constants --
    # the 2026-07-21 probe diagnosis (search finds the literal-substituted depth-2 form), caught
    # by the constancy check with no run.
    shape = make_ladder("al14-cell-row-grid").lint()
    assert _failed(shape, "constant-subterm[move_cell_up-00]")
    # al1 also enumerates constants and stays clean: the check fires on train-constant COMPOSITE
    # subterms, not on the mere presence of a constant domain.
    assert not any(
        f.check.startswith("constant-subterm") and not f.ok
        for f in make_ladder("al1-mirror").lint().findings
    )


def test_constant_subterm_downgrades_to_warn_without_a_constant_domain() -> None:
    # Same law, severity states whether the beating literal exists in THIS ladder's own search:
    # with no constant sources the enumerated domain is empty, so al14's constancy errors all
    # become fictional-depth warnings -- and nothing else fails al14's lint (which is exactly why
    # its 2026-07-20 certificate could only come back censored/inconclusive, not rejected).
    spec = make_ladder("al14-cell-row-grid")
    assert isinstance(spec.reference_config.search_engine, BottomUpSearchEngine)
    engine = dataclasses.replace(spec.reference_config.search_engine, constant_sources=())
    config = dataclasses.replace(spec.reference_config, search_engine=engine)
    shape = dataclasses.replace(spec, reference_config=config).lint()
    assert shape.ok
    downgraded = [
        f for f in shape.findings if f.check == "constant-subterm[move_cell_up-00]" and not f.ok
    ]
    assert len(downgraded) == 1 and downgraded[0].severity == "warn"


def test_lint_flags_a_degenerate_if_condition() -> None:
    # An If whose condition is constant across train examples collapses to the taken branch.
    spec = make_ladder("al1-mirror")
    top_solution = spec.top.reference_solutions[0]
    wrapped = If(cond=Const(True, BOOL), then=top_solution, orelse=top_solution)
    shape = dataclasses.replace(
        spec, top=dataclasses.replace(spec.top, reference_solutions=(wrapped,))
    ).lint()
    assert _failed(shape, f"if-condition-varies[{spec.top.task_ids[0]}]")


def test_floor_if_summoner_is_exercised_by_an_if_node() -> None:
    # `if` is summoned, never applied: an If node in a stated solution must count as exercising
    # the floor's `if` entry, or every conditional floor would read as dead vocabulary.
    spec = make_ladder("al1-mirror")
    floor = spec.floor().extended(name=f"{spec.floor().name}+if", extra=(IF,))
    config = dataclasses.replace(spec.reference_config, library=floor)
    with_if_idle = dataclasses.replace(spec, reference_config=config).lint()
    idle = next(f for f in with_if_idle.findings if f.check == "floor-fully-exercised")
    assert not idle.ok and "'if'" in idle.detail  # nothing uses branching yet

    demo = spec.rungs[0].demonstrations[0]
    branching = dataclasses.replace(
        demo, solution=If(cond=Const(True, BOOL), then=demo.solution, orelse=demo.solution)
    )
    rung = dataclasses.replace(
        spec.rungs[0], demonstrations=(branching, *spec.rungs[0].demonstrations[1:])
    )
    with_if_used = dataclasses.replace(
        spec, reference_config=config, rungs=(rung, *spec.rungs[1:])
    ).lint()
    used = next(f for f in with_if_used.findings if f.check == "floor-fully-exercised")
    assert used.ok


def test_free_param_variation_counts_every_call_site() -> None:
    # Variation that lives only in the SECOND call site of each demo must count: the proposer
    # sees every occurrence, and the old first-call-only read produced a false positive here.
    def demo(task_id: str, inner_color: int) -> Demonstration:
        inner = Apply("r", (Input(), Const(inner_color, COLOR)))
        return Demonstration(
            task_id=task_id,
            kind=DemonstrationKind.FULL_SOLUTION,
            solution=Apply("r", (inner, Const(1, COLOR))),
        )

    columns = _rung_argument_columns((demo("a", 2), demo("b", 3)), "r")
    # Column 1 is the grid slot (computed in the outer call, `input` in the inner) -- derived,
    # kept; column 2 is the colour, aggregating all four call sites: {1, 2, 3}.
    assert [index for index, _ in columns] == [1, 2]
    assert len(columns[1][1]) == 3


def test_lint_catches_the_al7_telescoping_statically() -> None:
    # The certificate found al7's skip paths empirically (2026-07-20); the rewrite check finds
    # them statically, witnesses printed -- and stays silent on the sound ladders.
    shape = make_ladder("al7-fast-tower").lint()
    assert _failed(shape, "rewrite-shallow[wide4]")
    assert _failed(shape, "rewrite-shallow[tall4]")
    assert _failed(shape, "rewrite-shallow[wide8]")
    for sound in ("al1-mirror", "al2-rot90-calibration"):
        assert not any(
            f.check.startswith("rewrite-shallow") and not f.ok
            for f in make_ladder(sound).lint().findings
        )
