"""``render_report_markdown``: the results.md artifact renderer (a pure formatter)."""

from __future__ import annotations

import re

from arc_lab.program_search.ladders.report import _fit_b_eff, render_report_markdown


def _compact(text: str) -> str:
    """Collapse table-cell padding so assertions are layout-independent."""
    return re.sub(r" +", " ", text)


_COST: dict[str, object] = {
    "jump_costs": {"rot180": 13486, "mirror_recolor": 13824},
    "jump_costs_to_first": {"rot180": 228, "mirror_recolor": 938},
    "top_jump_cost": 26401,
    "top_jump_cost_to_first": 7206,
    "laddered_marginal_considered": 53711,
    "laddered_marginal_to_first": 8372,
    "laddered_end_to_end_considered": 200280,
    "raw_considered": 6743,
    "raw_solved": False,
    "raw_censored": True,
    "off_chain_top_solved": True,
    "amortization_ratio_considered": None,
    "budget_compression_depth": {"raw_depth": 4, "max_jump_depth": 2},
}

_REPORT: dict[str, object] = {
    "ladder": {"train_corpus": {"name": "al1-mirror:train"}},
    "shape": {
        "height": 3,
        "raw_depth_profile": [4],
        "max_jump_depth": 2,
        "validity_window": [2, 2],
        "lint_ok": True,
    },
    "certificate": {
        "admitted": True,
        "tractable_jumps": {1: True, 2: True},
        "no_skip_paths": {1: True, 2: False},
        "demonstration_health": {1: 1.0, 2: 0.5},
    },
    "climb_trace": [
        {
            "iteration": 0,
            "wake_solved": ["rot180-00"],
            "wake_considered": 33715,
            "minted": ["abs0"],
            "converged": False,
        },
        {
            "iteration": 1,
            "wake_solved": [],
            "wake_considered": 34560,
            "minted": [],
            "converged": True,
        },
    ],
    "rung_recovery": [
        {"rung": "rot180", "level": 1, "recovered": True, "matched_by": ["abs0"]},
        {"rung": "mirror_recolor", "level": 2, "recovered": False, "matched_by": []},
    ],
    "cost_matrix": [
        {
            "task_id": "rot180-00",
            "rung": "rot180",
            "columns": {
                "0": {
                    "considered": 6743,
                    "solved": True,
                    "solve_generation": 2,
                    "first_solution_index": 114,
                    "cheapest_solution_index": 114,
                    "b_eff": 24.55,
                },
                "1": {
                    "considered": 6912,
                    "solved": False,
                    "solve_generation": None,
                    "first_solution_index": None,
                    "cheapest_solution_index": None,
                    "b_eff": None,
                },
            },
        }
    ],
    "comparisons": {
        "loop_overhead_factor": 200280 / 53711,
        "marginal_rung_value": [
            {
                "rung": "rot180",
                "layer_above": "mirror_recolor",
                "cost_without_rung": 13486,
                "cost_with_rung": 13824,
                "ratio": 13486 / 13824,
                "censored": True,
            }
        ],
        "vocabulary_tax": [
            {
                "rung": "rot180",
                "at_own_level": 13486,
                "at_full_library": 52802,
                "factor": 52802 / 13486,
            }
        ],
        "enablement": {"1": ["mirror-recolor-1-2"], "2": []},
    },
    "cost": _COST,
}


def test_renders_every_section_from_the_report_dict() -> None:
    text = _compact(render_report_markdown(_REPORT))
    assert "# Ladder results: al1-mirror" in text  # the :train suffix is stripped
    assert "**ADMITTED**" in text
    assert "| 1 | yes | yes | 1.0 |" in text and "| 2 | yes | no | 0.5 |" in text
    assert "| 0 | 1: `rot180-00` | 33,715 | `abs0` | no |" in text
    assert "| 1 | 0 | 34,560 | - | yes |" in text
    assert "| `mirror_recolor` | 2 | no | - |" in text
    assert "Laddered marginal: 53,711" in text and "- top jump: 26,401" in text
    assert "CENSORED" in text and "n/a (raw censored)" in text
    assert "d_raw 4 -> max jump depth 2" in text
    assert text.startswith("<!-- Generated by render_report_markdown")


def test_renders_cost_matrix_and_per_task_solution_detail() -> None:
    text = _compact(render_report_markdown(_REPORT))
    # Cost matrix: solved cells marked, unsolved bare (a censored lower bound).
    assert "| `rot180-00` | rot180 | 6,743 * | 6,912 |" in text
    # Per-task detail lists only solved cells, with generation + first/cheapest index + b_eff.
    assert "| `rot180-00` | L_0 | 2 | 114 | 114 | 6,743 | 24.55 |" in text
    assert "| `rot180-00` | L_1 |" not in text  # unsolved cell omitted from the detail table


def test_renders_comparisons_with_both_currencies() -> None:
    text = _compact(render_report_markdown(_REPORT))
    assert "### Two currencies -- read this first" in text
    assert "cost-paid-full: 53,711 vs cost-to-first: 8,372" in text
    assert "- jump `rot180`: 228" in text
    assert "**Loop-overhead factor**: 3.73x" in text
    assert "| `rot180` | mirror_recolor | 13,486 | 13,824 | 0.98x | yes |" in text
    assert "| `rot180` | 13,486 | 52,802 | 3.92x |" in text  # vocabulary tax
    assert "`L_1` (vs `L_0`): `mirror-recolor-1-2`" in text
    assert "`L_2` (vs `L_1`): nothing new" in text
    # The censoring caveat must be present so a sub-1.0x ratio is not read as a slowdown.
    assert "reachability" in text


def test_b_eff_fits_growth_only_over_pre_saturation_rounds() -> None:
    # Un-truncated rounds: composed 10 -> 40 -> 160 is a clean 4x per round.
    clean = [
        {"composed": 10, "pool_size_before_truncation": 10, "pool_size_end": 10},
        {"composed": 40, "pool_size_before_truncation": 40, "pool_size_end": 40},
        {"composed": 160, "pool_size_before_truncation": 160, "pool_size_end": 160},
    ]
    assert _fit_b_eff(clean) == 4.0
    # A round's composed count is a function of its INPUT pool, so the round that truncates its
    # own output is still a genuine measurement; only the round AFTER it composes from a capped
    # pool and would understate growth. Here 10 -> 40 -> 160 all count (4.0); the capped 200 does
    # not (including it would drag the fit to ~2.7).
    saturated = [
        *clean[:2],
        {"composed": 160, "pool_size_before_truncation": 900, "pool_size_end": 300},
        {"composed": 200, "pool_size_before_truncation": 900, "pool_size_end": 300},
    ]
    assert _fit_b_eff(saturated) == 4.0
    assert _fit_b_eff(clean[:1]) is None  # a single round yields no ratio


def test_ratio_renders_when_raw_is_uncensored() -> None:
    cost: dict[str, object] = {
        **_COST,
        "raw_considered": 500000,
        "raw_solved": True,
        "raw_censored": False,
        "amortization_ratio_considered": 500000 / 53711,
    }
    text = render_report_markdown({**_REPORT, "cost": cost})
    assert "Amortization considered-ratio: 9.31" in text
    assert "CENSORED" not in text
